"""MCP COBOL migration demo generator for CBACT01C.

This module provides a simple demo conversion path from the original COBOL source
into a Unisys MCP COBOL variant for review and incremental refinement.
"""

from __future__ import annotations

import os
import re
from pathlib import Path
from typing import Any, Dict, Optional

from langchain_core.messages import HumanMessage, SystemMessage
from langchain_google_genai import ChatGoogleGenerativeAI


def _read_source(project_root: Path, file_path: Optional[str], filename: Optional[str] = None) -> str:
    if file_path:
        source_path = Path(file_path)
        if not source_path.is_absolute():
            source_path = project_root / source_path
        if source_path.exists():
            return source_path.read_text(encoding="utf-8", errors="ignore")

    if not filename:
        filename = "CBACT01C.cbl"

    candidate_paths = [
        project_root / "carddemo" / "app" / "cbl" / filename,
        project_root / "carddemo" / "app" / "cpy" / filename,
        project_root / "aws-mainframe-modernization-carddemo" / "app" / "cbl" / filename,
        project_root / "aws-mainframe-modernization-carddemo" / "app" / "cpy" / filename,
        project_root / "app" / "cbl" / filename,
        project_root / "app" / "cpy" / filename,
        project_root / filename,
    ]
    for candidate in candidate_paths:
        if candidate.exists():
            return candidate.read_text(encoding="utf-8", errors="ignore")
    return ""


def _build_mcp_comment_block(program_id: str, is_copybook: bool = False) -> str:
    if is_copybook:
        header = [
            f"*> === Unisys MCP COBOL Copybook ===",
            f"*> Original: {program_id}",
            f"*> File Extension: c85_m (Unisys MCP COBOL format)",
            "*> Generated by demo migration UI",
            "",
        ]
    else:
        header = [
            f"*> === Unisys MCP COBOL Conversion ===",
            f"*> Original Program: {program_id}",
            f"*> File Extension: c85_m (Unisys MCP COBOL format)",
            "*> Generated by demo migration UI",
            "*> Review all COBOL dialect-specific syntax before deployment",
            "",
        ]
    return "\n".join(header)


def _normalize_source_for_mcp(source: str) -> str:
    if not source:
        return ""

    source = source.replace("\r\n", "\n").replace("\r", "\n")
    source_lines = source.split("\n")

    adapted_lines = []
    for line in source_lines:
        if re.match(r"^\s*IDENTIFICATION DIVISION\.", line, re.IGNORECASE):
            adapted_lines.append(line)
            continue
        if re.match(r"^\s*ENVIRONMENT DIVISION\.", line, re.IGNORECASE):
            adapted_lines.append(line)
            continue
        if re.match(r"^\s*DATA DIVISION\.", line, re.IGNORECASE):
            adapted_lines.append(line)
            continue
        if re.match(r"^\s*PROCEDURE DIVISION\.", line, re.IGNORECASE):
            adapted_lines.append(line)
            continue
        if "EXEC CICS" in line.upper() and "SECTION" not in line.upper():
            adapted_lines.append(line)
            continue
        adapted_lines.append(line)

    return "\n".join(adapted_lines)


def build_mcp_migration_context(loader: Any, program_id: str, project_root: str | Path) -> Dict[str, Any]:
    project_root = Path(project_root)
    details = {}
    try:
        details = loader.get_program_details(program_id) or {}
    except Exception:
        pass

    source = _read_source(project_root, details.get("file_path"))
    source_lines = source.splitlines()

    # Extract copybooks used by this program
    copybooks_used = []
    try:
        cur = loader.conn.cursor()
        cur.execute(
            "SELECT cu.copybook_name, c.file_path FROM copybook_usage cu "
            "LEFT JOIN copybooks c ON cu.copybook_name = c.copybook_name "
            "WHERE cu.program_id = ? ORDER BY cu.copybook_name",
            (program_id,),
        )
        copybooks_used = [{"name": row[0], "file_path": row[1]} for row in cur.fetchall()]
    except Exception:
        pass

    return {
        "program": {
            "program_id": program_id,
            "file_path": details.get("file_path"),
            "program_type": details.get("program_type"),
            "line_count": len(source_lines),
            "business_purpose": details.get("business_purpose"),
        },
        "source": source,
        "source_line_count": len(source_lines),
        "copybooks": copybooks_used,
        "evidence_source": "Original COBOL source file plus SQLite knowledge graph metadata.",
    }


def _extract_code(text: str) -> str:
    match = re.search(r"```(?:cobol)?\s*(.*?)```", text, flags=re.DOTALL | re.IGNORECASE)
    return match.group(1).strip() if match else text.strip()


def _fallback_mcp(context: Dict[str, Any]) -> str:
    program_id = context["program"].get("program_id", "CBACT01C")
    source = context.get("source", "")
    adapted_source = _normalize_source_for_mcp(source)
    comment_block = _build_mcp_comment_block(program_id, is_copybook=False)
    if adapted_source:
        return f"{comment_block}\n{adapted_source}"

    return (
        f"{comment_block}\n"
        "IDENTIFICATION DIVISION.\n"
        f"PROGRAM-ID. {program_id}.\n"
        "PROCEDURE DIVISION.\n"
        "    STOP RUN.\n"
    )


def _fallback_mcp_copybook(copybook_name: str, project_root: Path) -> str:
    """Generate a stub MCP copybook if source not found."""
    comment_block = _build_mcp_comment_block(copybook_name, is_copybook=True)
    return (
        f"{comment_block}\n"
        "       01  " + copybook_name + "-RECORD.\n"
        "           05  PLACEHOLDER-FIELD      PIC X(10).\n"
    )


def generate_mcp_for_program(
    loader: Any,
    program_id: str,
    project_root: str | Path,
    use_llm: bool = True,
) -> Dict[str, Any]:
    project_root = Path(project_root)
    context = build_mcp_migration_context(loader, program_id, project_root)
    gemini_api_key = os.environ.get("GEMINI_API_KEY")

    # Generate program code
    if use_llm and gemini_api_key:
        program_code = _generate_with_llm(context, program_id, gemini_api_key)
        used_llm = program_code != _fallback_mcp(context)
    else:
        program_code = _fallback_mcp(context)
        used_llm = False

    # Generate copybooks
    copybooks = {}
    for cb_info in context.get("copybooks", []):
        cb_name = cb_info.get("name")
        cb_path = cb_info.get("file_path")
        cb_source = _read_source(project_root, cb_path, f"{cb_name}.cpy") or _read_source(project_root, None, f"{cb_name}.cpy")
        adapted_cb = _normalize_source_for_mcp(cb_source)
        comment_block = _build_mcp_comment_block(cb_name, is_copybook=True)
        
        if adapted_cb:
            copybooks[cb_name] = f"{comment_block}\n{adapted_cb}"
        else:
            copybooks[cb_name] = _fallback_mcp_copybook(cb_name, project_root)

    return {
        "program_id": program_id,
        "mcp_code": program_code,
        "copybooks": copybooks,
        "context": context,
        "used_llm": used_llm,
    }


def _generate_with_llm(context: Dict[str, Any], program_id: str, gemini_api_key: str) -> str:
    """Generate MCP COBOL using Gemini LLM."""
    model_name = os.environ.get("GEMINI_MODEL", "gemini-2.5-flash")
    llm = ChatGoogleGenerativeAI(
        model=model_name,
        google_api_key=gemini_api_key,
        temperature=0.1,
        max_output_tokens=12000,
    )

    prompt = f"""
Convert COBOL program {program_id} into Unisys MCP COBOL format.

Use only the source and metadata in this conversion context. Preserve the original program structure and generate an MCP-style COBOL file that is suitable for Unisys MCP review.

Requirements:
- Keep the IDENTIFICATION, ENVIRONMENT, DATA, and PROCEDURE divisions.
- Keep COBOL paragraph names intact where possible.
- Convert the program to a valid MCP COBOL variant, with MCP comment style and any necessary syntax adaptations.
- Return only the COBOL source code, no markdown or explanation.

SOURCE:
{context.get('source')}
"""

    response = llm.invoke([
        SystemMessage(content="You are an expert Unisys MCP COBOL migration engineer. Return COBOL code only."),
        HumanMessage(content=prompt),
    ])

    mcp_code = _extract_code(response.content)
    return mcp_code if mcp_code else _fallback_mcp(context)


def generate_mcp_package(
    loader: Any,
    program_id: str,
    project_root: str | Path,
    use_llm: bool = True,
) -> Dict[str, Any]:
    """Generate MCP COBOL package with program and all copybooks as list of tuples.
    
    Returns:
        Dict with keys:
        - program_id: Program identifier
        - mcp_code: Generated MCP COBOL program code
        - copybooks: List of (name, mcp_code) tuples for each copybook
        - context: Migration context with metadata
        - used_llm: Boolean indicating if LLM was used
    """
    result = generate_mcp_for_program(loader, program_id, project_root, use_llm)
    
    # Convert copybooks dict to list of tuples for Streamlit
    copybooks_dict = result.get("copybooks", {})
    copybooks_list = [(name, code) for name, code in copybooks_dict.items()]
    
    return {
        "program_id": result["program_id"],
        "mcp_code": result["mcp_code"],
        "copybooks": copybooks_list,
        "context": result["context"],
        "used_llm": result.get("used_llm", False),
    }
